version: '3.8'

services:

  db:
    image: mysql/mysql-server:latest
    container_name: my-mysql
    restart: always
    environment:
      - MYSQL_DATABASE=mysqlDB
      - MYSQL_ROOT_PASSWORD=mysqlPW
    ports:
      - '3306:3306'
    volumes:
      - mysql-volume:/var/lib/mysql

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-volume:/var/lib/redis
    environment:
      - REDIS_PASSWORD=pegasus
      - REDIS_PORT=6379
      - REDIS_DATABASES=16

volumes:
  mysql-volume:
    driver: local
  redis-volume:
    driver: local
